### ISSUE TITLE
Intermittent failures when running 'examples/mcdta-7link.ipynb'

### ISSUE THREAD

**Issue by ghost** [maccmu/macposts#26]
I have noticed a few times that running 'examples/mcdta-7link.ipynb' failed randomly ([example](https://github.com/maccmu/macposts/actions/runs/5233329287/jobs/9448730316)). Usually such errors go away after a rerun.

I have not looked into it yet, but I think it happened mostly on macOS? Anyway, I think it created some noise and should be fixed.

**Comment by psychogeekir** [comment]
Yes, I observed that it usually happened to macOS with python 3.7 or 3.8.

**Comment by ghost** [comment]
Now we only check cells marked with `#NBVAL_CHECK_OUTPUT` magic comment (see 95c1e35bad8473af3e194fc1812a3788996694cf). So this is no longer a concern.
