### ISSUE TITLE
Release v0.4.0 CHANGELOG.md no such file

### ISSUE THREAD

**Issue by psychogeekir** [maccmu/macposts#39]
@kunhtkun Hi, I tried to release v0.4.0, but the workflow failed, it prompts

awk: fatal: cannot open file `CHANGELOG.md' for reading: No such file or directory

Could you please take a look at the Actions? Did I miss something?

Thanks,

**Comment by ghost** [comment]
Sorry I missed something. This should be fixed by #40.

**Comment by ghost** [comment]
#40 does not change the package ~so it is good to rerun the failed job and create the release.~ (No, I forgot it was created after the tag. Let's tag a new one.) However, I also notice that the version number is not correct in https://github.com/maccmu/macposts/blob/4387b3edebc061e8843f576c1f838fa89c65e154/macposts/__init__.py#L8

Maybe we should skip 'v0.4.0' and make a hot fix release 'v0.4.1'.

**Comment by psychogeekir** [comment]
Thanks, will do
