### ISSUE TITLE
compilation error of SNAP

### ISSUE THREAD

**Issue by psychogeekir** [maccmu/macposts#47]
I encountered this issue in my compilation which seems new to me... can @kunhtkun please take a look? many thanks 

[build] In file included from /home/qlzou/Documents/CodeBase/maccmu_github/macposts/lib/snap/snap-core/Snap.cpp:24:
[build] /home/qlzou/Documents/CodeBase/maccmu_github/macposts/lib/snap/snap-core/table.cpp:785:5: error: use of undeclared identifier 'LoadSSPar'
[build]     LoadSSPar(T, S, InFNm, RelevantCols, Separator, HasTitleLine);
[build]     ^
[build] 1 error generated.

**Comment by psychogeekir** [comment]
Well, after changing the compiler from Clang to GCC, this issue seems resolved.

**Comment by ghost** [comment]
It seems that you did not have OpenMP for your Clang toolchain. Should be fixed by https://github.com/maccmu/snap/pull/1.

**Comment by psychogeekir** [comment]
Thank you! I used Clang before on babyam and had no such issues and not sure why I came across it this time...

**Comment by ghost** [comment]
Might be due to the Debian upgrade we did in December. Perhaps OpenMP is not shipped with Clang anymore in Debian 12.
